### ISSUE TITLE
Differences to slightfoot/flutter_sticky_headers

### ISSUE THREAD

**Issue by levrik** [letsar/flutter_sticky_header#1]
What are the actual differences to slightfoot/flutter_sticky_headers in the implementation? Which implementation is better?

Would be nice to get a few questions answered that help picking one of the two libraries :)

**Comment by letsar** [comment]
Hi @levrik! This is a very good question.
The difference is in the kind of widgets you want to put as a child:
The slightfoot/flutter_sticky_headers wants a **RenderBox** as a child while this package wants a **RenderSliver**.

For example the **Column** widget renders a **RenderBox**, whereas the **SliverList** renders a **RenderSliver**.
So the **Column** widget will work with the slightfoot/flutter_sticky_headers but not the **SliverList**. 

With this package you can do both :wink:!

What :hushed:? I said that this package wants a **RenderSliver** and the **Column** widget does not provide one! Yes that's true, but with the **SliverToBoxAdapter** widget you can put a **RenderBox** element in it and it will be rendered as a **RenderSliver** :astonished:!

So if you use this package you can do **both** :smiley:!

Moreover, the intended use of headers is typically for lists with a lot of items. And for lists, the **SliverList** is a better choice than a **Column**.

If this answer explains in an understandable way the difference, I will put it in the README, to help people to choose :wink:.

**Comment by tamoyal** [comment]
@letsar This was helpful for me and I think belongs in the README with potentially some elaboration on why this will perform better on big lists.

**Comment by pkitatta** [comment]
Was helpful thanks. Being new to flutter sometime you can know the advantages.
