### ISSUE TITLE
Package is broken due to FLUTTER UPGRADE 3.27

### ISSUE THREAD

**Issue by stan-at-work** [letsar/flutter_sticky_header#102]
Your package is broken deu to the latest flutter release: Please fix https://github.com/letsar/flutter_sticky_header/issues/99 ASAP

**Comment by saropa** [comment]
Same here

**Comment by stan-at-work** [comment]
@saropa https://github.com/letsar/flutter_sticky_header/issues/99#issuecomment-2538710526

**Comment by stan-at-work** [comment]
Fixed as discribed: https://github.com/letsar/flutter_sticky_header/issues/99#issuecomment-2538710526
