### ISSUE TITLE
How I can build infinite scroll?

### ISSUE THREAD

**Issue by TatsuUkraine** [letsar/flutter_sticky_header#16]
So case here. I want to build infinite both-direction list and split sections with sticky headers.
How I can do this with your plugin (if it's possible in general)?

P.S. To make both-direction infinite list I used Viewport with 2 SliverList instances, and "center" key, that points to positive direction list

**Comment by TatsuUkraine** [comment]
@ened @letsar any update on this?) or any answer maybe)

**Comment by TatsuUkraine** [comment]
Good example is google calendar, agenda view. With sticky dates

**Comment by TatsuUkraine** [comment]
While I was waiting for a response I actually build my own implementation to solve this 😅

**Comment by letsar** [comment]
Ok, so I can close this then. Sorry for the delay ^^

**Comment by TatsuUkraine** [comment]
@letsar I was hoping that you can recommend how this can be achieved with your package though)

**Comment by Dohmanlechx** [comment]
> While I was waiting for a response I actually build my own implementation to solve this 😅

@TatsuUkraine Probably a longshot two years later, but can you please show your implementation? I'm struggling very hard with this, I'm almost convinced that this package has no support for infinite scroll. I've used this package multiple times, all good, but every time it was a finite scroll.

@letsar Do you have an example of an infinite scroll with sticky headers? Like if I want to build a "calendar list" with sticky (infinite) dates.

**Comment by TatsuUkraine** [comment]
> can you please show your implementation

@Dohmanlechx I don't know if it's ok to advertise my package here 😅 but current issue has a link to awesome-flutter repo (a few messages above). You can look there for a reference to my package, also it has links to other sticky header solutions with description of  drawbacks, but maybe those issues already solved.

**Comment by Dohmanlechx** [comment]
> @Dohmanlechx I don't know if it's ok to advertise my package here 😅 but current issue has a link to awesome-flutter repo (a few messages above). You can look there for a reference to my package, also it has links to other sticky header solutions with description of drawbacks, but maybe those issues already solved.

Oh, didn't realize there was a reference to another package!

So I was right after all, that this package doesn't support infinite scroll or at least doesn't provide an example for it ([every example](https://github.com/letsar/flutter_sticky_header/tree/master/example/lib/examples) in the repository uses a fixed list of items). I am relieved knowing this haha, I struggled way too hard! Thank you for making this "longshot" a miracle and I will either use your package or just go with non-sticky headers.
