### ISSUE TITLE
Please support setting offset display floating head

### ISSUE THREAD

**Issue by Thomaszhouwu** [letsar/flutter_sticky_header#18]
First of all, thank you.
Please support the distance property from the previous control.

**Comment by Thomaszhouwu** [comment]
Now, the distance of the floating head from the previous control is 0. I think the distance from the previous control can be set by itself. Thank you.

**Comment by letsar** [comment]
Hi @Thomaszhouwu, if you set a Padding into your header, you can achieve what you want I think.

**Comment by Thomaszhouwu** [comment]
Thank you for your reply。

my code:
![111](https://user-images.githubusercontent.com/8766976/51510978-64d30c00-1e3a-11e9-8022-8d14060578dd.png)

SliverStickyHeader(
        header: Padding(
          padding: EdgeInsets.only(top: 64),
          child: GrouponThemeFilterTabar(
            tabTitles: tabTitles,
          ),
        )
If I add Padding, I will leave extra space from the previous control.

Please see my attachment.

**Comment by Thomaszhouwu** [comment]
The head navigation bar is my custom navigation bar.

**Comment by Thomaszhouwu** [comment]
I want the position of the head to float and I can control it myself.

**Comment by charmfocus** [comment]
yes, It's the same as mine.
please support the feature, thank's

**Comment by natrayanp** [comment]
Please support the feature.  I have the same issue.

**Comment by emvaized** [comment]
I have the same issue too.
@letsar Please add support for floating SliverAppBar.

**Comment by emvaized** [comment]
@Thomaszhouwu 
I found the solution -- you just have to wrap your main `Scaffold` in `SafeArea` widget.
