### ISSUE TITLE
_buildHeader unable to access class level json variable

### ISSUE THREAD

**Issue by vijayredme** [letsar/flutter_sticky_header#21]
@letsar : I am trying to make the header content dynamic instead of just an index. I have a class level variable which holds a local json data, when I am trying to access that variable inside _buildHeader() method it is always null, Wherein I am able to access same variable in other method which is being called from SliverChildBuilderDelegate's ListTile.  Any clue what could be the issue ?

**Comment by letsar** [comment]
Without some code, not really. This seems to be a general question and I don't think the issue is related to this package.
