### ISSUE TITLE
Question - Expansion tile like behaviour

### ISSUE THREAD

**Issue by kostaa** [letsar/flutter_sticky_header#31]
How would one go about adding an expansion tile like behaviour so the children would expand/collapse similar to the Flutter [ExpansionTile](https://flutter.dev/docs/catalog/samples/expansion-tile-sample) behaviour?

Is the [Expansionable support #22](https://github.com/letsar/flutter_sticky_header/issues/22) issue related to this?

**Comment by letsar** [comment]
Not the purpose of this package sorry.
