### ISSUE TITLE
Add flutter_sticky_header to Flutter Arsenal

### ISSUE THREAD

**Issue by flutter-arsenal** [letsar/flutter_sticky_header#33]
flutter_sticky_header can be added to FlutterArsenal to help with reach, accessibility and ease-of-use. [Flutter Arsenal](https://flutterarsenal.com) is a directory that is being curated for Flutter libraries and tool. The best way to do is by creating an issue on [github](https://github.com/flutterarsenal/FlutterArsenal/issues/new/choose).

**Comment by f-person** [comment]
It's already [added](https://flutterarsenal.com/projects/fa-git-flutter-sticky-header). @letsar please close the issue.
