### ISSUE TITLE
How to setup the list data?

### ISSUE THREAD

**Issue by trqalothman** [letsar/flutter_sticky_header#37]
Hello Romain,

Great work on this package.  It would be really great if you could help us beginners in dart/flutter with a small example on how to setup/prepare our data in the list and how to use the package with it.  my data is structured in a key:value pairs inside a list.  

`mylist = [
{name: 'ABC',  age: 23,  date: 2019-11-27},
{name: 'DEF', age: 35, date: 2019-11-26}]`

and I want to extract the dates to be the headers and group all list items which belong to the same date under it.  The number of items per date changes from one date to another based on the fetched data. The example attached is very hard to understand for beginners as all the lists and headers are generated with code.

Thank you so much.

**Comment by trqalothman** [comment]
Anyone? on how the data should be structured and how to call the methods in the package?
thanks

**Comment by deepak786** [comment]
@trqalothman how did you manage to solve this?
I will have the data:
```
mylist = [ {name: 'ABC', age: 23, date: 2019-11-27}, {name: 'ABC', age: 23, date: 2019-11-27}, {name: 'ABC', age: 23, date: 2019-11-27}, {name: 'DEF', age: 35, date: 2019-11-26}, {name: 'DEF', age: 35, date: 2019-11-26}]
```

I want the date field to be sticky so that data related to the same date will be under one header.

**Comment by trqalothman** [comment]
@deepak786
the way I solved this is by having two step process, first I query only the dates list that will be the headers

`SELECT DISTINCT DATE FROM ... WHERE [DATE RANGE YOU DESIRE]`

storing the result in a list, and then iterating through the headers list i create another list for the items inside each date

`SELECT * FROM .... WHERE DATE = [DATE VALUE FROM OUTER ITERATION]`

then you send the two lists to the package, this is the only way that I thought could be possible to deal with the data structures that I have.  Nested loops, outer loop for the headers, inner loop for the items inside each header.  Hope this helps.

Good luck, happy coding :)
