### ISSUE TITLE
A RenderCustomMultiChildLayoutBox expected a child of type RenderBox but received a child of type RenderSliverStickyHeader.

### ISSUE THREAD

**Issue by misskter** [letsar/flutter_sticky_header#39]
I use this library has this error

A RenderCustomMultiChildLayoutBox expected a child of type RenderBox but received a child of type RenderSliverStickyHeader.

RenderObjects expect specific types of children because they coordinate with their children during layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a RenderSliver does not understand the RenderBox layout protocol.
The RenderCustomMultiChildLayoutBox that expected a RenderBox child was created by: CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#ba9f9 ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← AnimatedPhysicalModel ← Material ← PrimaryScrollController ← _ScaffoldScope ← Scaffold ← ⋯
The RenderSliverStickyHeader that did not match the expected child type was created by: SliverStickyHeader ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#ba9f9 ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← AnimatedPhysicalModel ← ⋯
The relevant error-causing widget was: 
  Scaffold file:///home/dev_03/flutter-app/test_header/lib/main.dart:69:12
When the exception was thrown, this was the stack: 
#0      ContainerRenderObjectMixin.debugValidateChild.<anonymous closure> (package:flutter/src/rendering/object.dart:2993:9)
#1      ContainerRenderObjectMixin.debugValidateChild (package:flutter/src/rendering/object.dart:3020:6)
#2      MultiChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:5509:25)
#3      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5295:35)
#4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5058:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

My development environment is like this:
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 周前) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Comment by letsar** [comment]
You cannot use a Sliver in a CustomMultiChildLayout. This package is only intended to be used in a scroll view (like CustomScrollView).
