### ISSUE TITLE
SliverStickyHeaderBuilder: add isPinned parameter

### ISSUE THREAD

**Issue by DanielSparber** [letsar/flutter_sticky_header#4]
Is it possible to add an additional paramater to the builder function? I.e. to indicate if the header is currently fixed at the top or positioned normally within the scroll view:

For this example isPinned would be true for Header#10 and false for any other visible header.

![grafik](https://user-images.githubusercontent.com/8910833/41962271-e098d9d6-79f4-11e8-9f53-cbb24733001b.png)

**Comment by letsar** [comment]
Hi @DanielSparber. 
I will work on this this week-end. I'll keep you posted.

**Comment by letsar** [comment]
I've got something working in the branch: https://github.com/letsar/flutter_sticky_header/tree/feature/pinned-state.

![sticky_header_pinned](https://user-images.githubusercontent.com/9378033/42121763-7d25337a-7c35-11e8-82e0-0fe25547bdf2.gif)

If this what you had in mind I will publish it.

**Comment by DanielSparber** [comment]
Yes, it's exactly what I had in mind. Thanks a lot!

**Comment by letsar** [comment]
Merged and published, have fun!
