### ISSUE TITLE
Add alphabetic shortcut like it's done on contact apps

### ISSUE THREAD

**Issue by sgruhier** [letsar/flutter_sticky_header#41]
I needed alphabetic shortcut on the right side, like you can have on contact applications for example.
I did something that works, but I'm wondering if there were an easy way to get all section offsets? 
My implementation precompute all offset at first rendering. I also generate  that ABCD...Z shortcuts on the right (see screenshot)

It would be nice to have that available in that component

![image](https://user-images.githubusercontent.com/3385/72626764-8b435e80-394b-11ea-9713-59bd32b15f28.png)

**Comment by DNetORM** [comment]
you can  use GlobalKey.
I used globalkey to solve it.Give you some core code for reference
 
  List<GlobalKey> itemKeys = [];
  GlobalKey headkey = new GlobalKey();

headkey is use to get  the appbar bottom offset1,itemKey is use to get the  item widget offset2,then offset2-offset1 is the scroll position.

      List data = response.data["Categories"];
      data.forEach((m) => itemKeys.add(new GlobalKey()));

 Widget _renderProductWithKey(Product item, int index) {
    return Container(
      key: itemKeys[index],
      padding: EdgeInsets.only(left: 80, top: 6, bottom: 6, right: 10),
      child: Row(.....

 var wgits = categorys.map((m) {
        var index = categorys.indexOf(m);
        return SliverStickyHeader(
          header: new Container(
            height: 35.0,
            color: Colors.white,
            padding: EdgeInsets.only(left: 80.0),
            alignment: Alignment.centerLeft,
            child: new Text(
              m.categoryName,
              style: const TextStyle(color: Colors.black87),
            ),
          ),
          sliver: new SliverList(
            delegate: new SliverChildBuilderDelegate((context, i) {
              if (i == 0) {
                return _renderProductWithKey(m.products[i], index);
              } else {
                return _renderProduct(m.products[i]);
              }
            }, childCount: m.products.length),
          ),
        );

   if (item.offset == null) {
                            RenderBox renderBoxHead =
                                headkey.currentContext.findRenderObject();
                            var offsetHead =
                                renderBoxHead.localToGlobal(Offset.zero);
                            print(offsetHead.dy);
                            RenderBox renderBox = itemKeys[index]
                                .currentContext
                                .findRenderObject();

                            var offset = renderBox.localToGlobal(Offset.zero);
                            print(offset.dy);
                            item.offset = offset.dy - offsetHead.dy - 35;
                          }

                          print(item.offset);
                          var value = item.offset;
                          if (value >
                              _scrollController.position.maxScrollExtent) {
                            value = _scrollController.position.maxScrollExtent;
                          }
                          _scrollController.jumpTo(value);

**Comment by letsar** [comment]
This is not the purpose of this package.
