### ISSUE TITLE
Programmatically Scroll to a certain header

### ISSUE THREAD

**Issue by sofman98** [letsar/flutter_sticky_header#47]
I’m trying to create a custom widget composed of two scrollable items (like a ListView) next to each other. The one on the right contains the main data separated into different sections (same List), the one on the left contains the sections (or shortcuts) of the right one. For example, if I press on the third item of the left List, I would be automatically scrolled down to the third section of the right List. The items don’t have the same height.
Here’s a video that shows what I’m looking for
I used a sticky header but I didn't find a way to programmatically scroll to any of them.
any help please?
![video-1587432200](https://user-images.githubusercontent.com/47697774/79815090-b2a92d80-8377-11ea-91ff-b819b0b48f85.gif)

**Comment by jamesdixon** [comment]
@sofman98 did you ever find a method to do this?

**Comment by sofman98** [comment]
> @sofman98 did you ever find a method to do this?

Unfortunately not exactly as in the video, however I did use a package that permitted to scroll to a certain index. I don’t exactly remember its name though..

**Comment by letsar** [comment]
You can use https://pub.dev/packages/scroll_to_index in combination with this package to achieve what you want.
