### ISSUE TITLE
Build StickyHeaders dynamicly

### ISSUE THREAD

**Issue by mehrdad-shokri** [letsar/flutter_sticky_header#52]
Hi, thanks for your library this is not an issue/bug with this library. I'm stuck on generating ``StickyHeader`` as a builder pattern.  I want to create a finite list just like ``ListView.Builder`` but with ``CustomScrollView``. More detail can be found [here](https://stackoverflow.com/questions/63528677/builder-pattern-slivers-passed-to-customscrollview) sorry again for opening this issue

**Comment by letsar** [comment]
Can you elaborate?

You can do something like this:
```dart
return CustomScrollView(
      slivers: [
        ...groups.map(
          (group) {
            return SliverStickyHeader(
              header:Text(group.title),
              sliver: SliverList(
                delegate: SliverChildBuilderDelegate(
                  (BuildContext context, int index) {
                    return Text(group.items[index].label);
                  },
                  childCount: group.items.length,
                ),
              ),
            );
          },
        ),
      ],
    );
```

**Comment by mehrdad-shokri** [comment]
I'm creating upcoming page of a todo app. user can scroll indefinitely so ``groups`` isn't something I want. Besides, Items should be created dynamically inside ``slivers``

**Comment by romaopedro** [comment]
@letsar I want to achieve the result of your example.
`elements.map` won't work because it returns an `Iterable` and we need a Widget Element.

I tried using SliverList to generate multiple widgets and List.generate, but none of them worked, I got multiple errors from the compiler.
This is my example
```
slivers: [
  SliverList(
    delegate: SliverChildBuilderDelegate(
      (BuildContext context, int index) {
        return SliverStickyHeader(
          header: Container(
            height: 60.0,
            color: Colors.lightBlue,
            padding: EdgeInsets.symmetric(horizontal: 16.0),
            alignment: Alignment.centerLeft,
            child: Text('Header #0'),
          ),
          sliver: SliverList(
            delegate: SliverChildBuilderDelegate(
              (context, i) => ListTile(
                leading: CircleAvatar(
                  child: Text('0'),
                ),
                title: Text('List tile #$i'),
              ),
              childCount: 4,
            ),
          ),
        );
      },
      childCount: 5,
    ),
  )
]
```

**Comment by astubenbord** [comment]
Did you find a solution on how to lazy-load StickyHeaders?
