### ISSUE TITLE
Version 0.4.6 requires Fluter 1.20+ because of transitive dependency, breaks 

### ISSUE THREAD

**Issue by jaysephjw** [letsar/flutter_sticky_header#54]
As you are maybe aware version 0.4.6 uses flutter_layout_builder 0.1.0 which implicitly requires flutter 1.20+, which I'm not on yet. This broke after upgrade for me, with my non-breaking version constraint on sticky_header.

If 0.5.0 is just to get out .4.6's changes with proper version constraint, maybe consider publishing an 0.4.7 that reverts 0.4.6's new dependency? I don't know if that's best practice, but it would be a way to fix non-breaking upgrades for .4.X users. 

(p.s., thanks for the package!)

**Comment by letsar** [comment]
Hi @jaysephjw, I'm not sure I would be able to publish a new version with a semver older than the currently one.

**Comment by Kingtous** [comment]
facing the same issue... Downgrade to 0.4.5 may work.

**Comment by jaysephjw** [comment]
Yup was no big issue for me, just fix to 0.4.5 until I am ready for Flutter 1.20+.
