### ISSUE TITLE
is there is a way to scroll to a particular header using its index or any other way?

### ISSUE THREAD

**Issue by ehabreda** [letsar/flutter_sticky_header#69]
Thanks for this useful library..
in my use case I will group a list of matches by its dates, a few matches every day, and today's date should be in the middle of let us say 2 weeks, one week in the past and another week into the future.
is there is a way to scroll to today's header using it's index?

Thanks

**Comment by letsar** [comment]
Hello, your can use https://pub.dev/packages/scroll_to_index package to achieve what you want.
