### ISSUE TITLE
off by one pixel

### ISSUE THREAD

**Issue by SteveAlexander** [letsar/flutter_sticky_header#8]
I'm noticing a one pixel difference at the top when I use a CustomScrollView containing a SliverList, and a CustomScrollView using SliverStickyHeader.

![image](https://user-images.githubusercontent.com/4321921/43995857-f9a9fd6e-9dae-11e8-87b3-ba0765a781d2.png)

To reproduce, clone https://github.com/SteveAlexander/one_pixel_bug
then tap in the text area at the top of the screen so that it gets focus.

Notice that the 2px blue border on the TextField is covered by the SliverStickyHeader by 1px.

This does not happen when using regular Slivers in a CustomScrollView.

**Comment by letsar** [comment]
Hi @SteveAlexander,

Thanks a lot for the project to reproduce this issue 😃.
I am able to reproduce and I will look into it.

**Comment by letsar** [comment]
Ok, I looked into it, but I don't think this issue is caused by the `SliverStickyHeader` widget.
If I insert the following code before the `SliverStickyHeader` I have also the same issue:

```dart
SliverPadding(
  padding: EdgeInsets.symmetric(horizontal: 20.0),
  sliver: SliverToBoxAdapter(
    child:
        Container(width: 10.0, height: 30.0, color: Colors.red),
  ),
),
```
![screenshot_1534669502](https://user-images.githubusercontent.com/9378033/44307350-190acb00-a3a1-11e8-8c08-032f89b637ce.png)

If I replace the `TextField` by a `Container `of 2px, there are no more issues:
![screenshot_1534669259](https://user-images.githubusercontent.com/9378033/44307367-6b4bec00-a3a1-11e8-9ff6-437984e4a92b.png)

So I bet this is more an issue with the `InputDecoration` of the `TextField` than with the `SliverStickyHeader`.

**Comment by SteveAlexander** [comment]
That makes sense! Thanks for checking it out. And, thanks for making flutter_sticky_header too — I'm using it a lot.

I have a workaround for my app, placing the TextField in a Padding with 1px on the bottom.

But it would be good to get this fixed in flutter too — I'm happy to file a bug on flutter... or perhaps you're already doing so?

**Comment by letsar** [comment]
Thanks for your feedback 😄.
No I didn't file this bug to the flutter repo, I leave you the privilege 😄. Feel free to reference it from here, in case others find the same issue.

**Comment by vanlooverenkoen** [comment]
Could be related? https://github.com/flutter/flutter/issues/37578

**Comment by vanlooverenkoen** [comment]
Any progress on this issue?

**Comment by trqalothman** [comment]
I am facing the same issue.  It is very obvious on iPhone 6, iOS v12.5.5.  I have a container with a `CustomScrollView` and it is leaving a transparent 1-pixel line between the top of the sticky header and the container.

Default settings for `CustomScrollView` to have `clipBehavior: Clip.HardEdge`.  I changed this to be `clipBehavior: Clip.antiAlias` and it does help making it less visible.  Hope this helps.

**Comment by kingglov** [comment]
i am facing the same issue but finally
![WhatsApp Image 2022-04-13 at 12 57 31 PM](https://user-images.githubusercontent.com/50819408/163123333-df18f213-c59a-482d-ae90-7d1d9623a4e3.jpeg)
![WhatsApp Image 2022-04-13 at 12 57 30 PM](https://user-images.githubusercontent.com/50819408/163123347-c37d7fc5-21ab-44fa-b4ef-610c1f850ba5.jpeg)
fixed this by adding container with same color to the bottom of Sliverapp bar
`SliverAppBar(
              bottom: PreferredSize(
                preferredSize: Size(double.infinity, 1),
                child: Container(
                  height: 1,
                  decoration: BoxDecoration(
                    color: Colors.transparent,
                    boxShadow: [
                      BoxShadow(
                        color: Color.fromARGB(255, 34, 34, 34),
                        blurRadius: 0.0,
                        spreadRadius: 1.0,
                        blurStyle: BlurStyle.inner,
                        offset: Offset(0, 0),
                      ),
                    ],
                  ),
                ),
              ),
              backgroundColor: Colors.black87,`

**Comment by vanlooverenkoen** [comment]
@letsar is this fixed?
