### ISSUE TITLE
rtl support 

### ISSUE THREAD

**Issue by liadya** [letsar/flutter_sticky_header#9]
Please add support for right to left layouts/languages (Hebrew for example), 
for example, cannot change the location of the SliverStickyHeader.header to be located on the right side of the list.

**Comment by letsar** [comment]
Hi @liadya,
Thanks for this issue, I will add this to the next version 😃 !

**Comment by letsar** [comment]
I ran more tests and in fact, my header was built like this:
```dart
return new Container(
  height: 60.0,
  color: Colors.lightBlue,
  padding: EdgeInsets.symmetric(horizontal: 16.0),
  alignment: Alignment.centerLeft,
  child: new Text(
    text ?? 'Header #$index',
    style: const TextStyle(color: Colors.white),
  ),
);
```
In my case the `alignment` was hard coded to `centerLeft`. 

If I only set a `Text`, it is correctly rendered with the proper text direction. So this widget already supports Ltr and Rtl  text directions 😃.

Can you paste here the method you used to create your headers?

**Comment by liadya** [comment]
Hi Roman,

thanks for the response, but currently we move forward with another
implementation.

ps. btw great widget.

**Comment by letsar** [comment]
Hi @liadya ,

Ok no problem, I will close this issue then.
With which implementation did you move forward?

Thanks for your feedback 😃
