### ISSUE TITLE
For UnderKoen's  - fork :Please fix slivers scrolling above header

### ISSUE THREAD

**Issue by DennisMuchiri** [letsar/flutter_sticky_header#95]
https://github.com/UnderKoen/flutter_sticky_header/tree/master
@UnderKoen please fix your fork slivers: scrolling above header. Thank you.

**Comment by UnderKoen** [comment]
As discussed in https://github.com/letsar/flutter_sticky_header/pull/67 the prefered method for multiple slivers is MultiSliver. So I won't be updating my fork.

**Comment by DennisMuchiri** [comment]
Great closing
